#!/bin/bash
# dsearch
# dmenu script which can search many websites for keywords and open the results in your browser
# 03-05-2022
# Licensed under GNU GPLv3.

# Import configuration
DSEARCH_IMPORT()
{
  DSEARCH_DEFAULT_CONFIGURATION
  . ~/.config/dsearch/dsearchrc
}

# Run a few things that need to run
DSEARCH_INIT()
{
  echo "DSEARCH has been loaded!" && DSEARCH_HAS_BEEN_LOADED=true
}

DSEARCH_DEFAULT_CONFIGURATION()
{
  DSEARCH_DOTDIR=~/.config/dsearch # Where your dotfiles are
  DSEARCH_DMENU=/usr/bin/dmenu # Path to dmenu
  DSEARCH_BROWSER=$BROWSER # Web browser to open results in
  DSEARCH_SHELL="/bin/sh -c" # Shell to use
  DSEARCH_SEARCHENGINE="$(cat $DSEARCH_DOTDIR/SEARCH.USE || cat ~/.config/dsearch/SEARCH.USE)" # Website/Service to search
  # Examples:
  # https://searx.org/search?q=
  # https://www.google.com/search?q=
  # https://stackoverflow.com/search?q=
  # https://duckduckgo.com/?q=
  # https://wiki.archlinux.org/index.php?search=
  # https://wiki.gentoo.org/index.php?search=
}

DSEARCH_CHECKDEP()
{
  ls $DSEARCH_DMENU || DSEARCH_DIE
}

DSEARCH_DIE()
{
  echo "Exiting (1)" && exit 1
}

DSEARCH_EXIT()
{
  echo "Exiting (0)" && exit 0
}

DSEARCH_IMPORT # Import configuration file from either variable or predefined directory
DSEARCH_CHECKDEP # Check to make sure all dependencies are installed
DSEARCH_INIT # Init

DSEARCH_SEARCH="$(printf "Enter search terms\nChange Search Engine\nExit" | $DSEARCH_DMENU)" && query="$(printf "$DSEARCH_SEARCH" | sed 's| |+|g')"

# Add a Change Search Engine option
case "$DSEARCH_SEARCH" in
    "Change Search Engine") DSEARCH_MENU="DSEARCH_CHANGE_ENGINE" ;;
	"Exit") DSEARCH_EXIT ;;
esac

case "$DSEARCH_MENU" in
    "DSEARCH_CHANGE_ENGINE") DSEARCH_SELECTED="$(printf "$(ls $DSEARCH_DOTDIR/SEARCH_ENGINES)\nExit" | $DSEARCH_DMENU)" && cat $DSEARCH_DOTDIR/SEARCH_ENGINES/$DSEARCH_SELECTED > $DSEARCH_DOTDIR/SEARCH.USE && DSEARCH_EXIT ;;
    "") DSEARCH_EXIT
esac

$DSEARCH_BROWSER ${DSEARCH_SEARCHENGINE}${query} && printf "Searched successfully!" && exit 0
